import React, { useState } from 'react';
import { Card, CardContent } from "@/components/ui/card";
import {
  Building2,
  TrendingUp,
  Rocket,
  Shield,
  Award,
  BarChart3,
  Users,
  PieChart,
  FileText,
  Home,
  DollarSign,
  Percent,
  Clock,
  Search,
  Star,
  Target,
  Lightbulb,
  Briefcase,
  CheckCircle,
  ArrowUpRight,
  Building,
  Landmark,
  TrendingDown,
  HandCoins,
  Coins,
  Banknote,
  Receipt,
  Scale,
  FileCheck,
  Layers,
  Globe,
  Zap
} from "lucide-react";

export default function Features() {
  const [activeTab, setActiveTab] = useState("fractional");
  const [reitType, setReitType] = useState("reit");

  // Feature data for each investment type
  const investmentFeatures = {
    fractional: [
      {
        title: "Direct Ownership",
        description: "Own a fraction of high-value properties with complete legal rights",
        icon: <Building2 className="w-8 h-8 text-blue-600" />
      },
      {
        title: "Low Entry Barrier",
        description: "Start investing with as little as ₹25,000 in premium properties",
        icon: <DollarSign className="w-8 h-8 text-green-600" />
      },
      {
        title: "Regular Rental Income",
        description: "Receive monthly rental income proportional to your ownership share",
        icon: <Coins className="w-8 h-8 text-yellow-600" />
      },
      {
        title: "Property Appreciation",
        description: "Benefit from capital appreciation as property value increases",
        icon: <TrendingUp className="w-8 h-8 text-purple-600" />
      },
      {
        title: "Transparent Pricing",
        description: "Clear, transparent pricing with no hidden fees or charges",
        icon: <Scale className="w-8 h-8 text-indigo-600" />
      },
      {
        title: "Easy Exit Options",
        description: "Sell your fraction anytime through our secondary marketplace",
        icon: <ArrowUpRight className="w-8 h-8 text-red-600" />
      }
    ],
    reit: [
      {
        title: "Diversified Portfolio",
        description: "Invest in a professionally managed portfolio of income-generating properties",
        icon: <PieChart className="w-8 h-8 text-blue-600" />
      },
      {
        title: "High Liquidity",
        description: "Easily buy and sell units on stock exchanges like any other security",
        icon: <Zap className="w-8 h-8 text-green-600" />
      },
      {
        title: "Regular Dividends",
        description: "Receive consistent dividend payouts from rental income generated by properties",
        icon: <Banknote className="w-8 h-8 text-yellow-600" />
      },
      {
        title: "Professional Management",
        description: "Properties managed by experienced real estate professionals",
        icon: <Briefcase className="w-8 h-8 text-purple-600" />
      },
      {
        title: "Tax Benefits",
        description: "Potential tax advantages including pass-through taxation benefits",
        icon: <Receipt className="w-8 h-8 text-indigo-600" />
      },
      {
        title: "Regulated Investment",
        description: "SEBI regulated investment product with investor protection measures",
        icon: <Shield className="w-8 h-8 text-red-600" />
      }
    ],
    smreit: [
      {
        title: "Small Ticket Size",
        description: "Invest with smaller amounts starting from ₹10,000 in select properties",
        icon: <DollarSign className="w-8 h-8 text-blue-600" />
      },
      {
        title: "Asset Specific",
        description: "Invest in a single property or a small portfolio of similar properties",
        icon: <Building className="w-8 h-8 text-green-600" />
      },
      {
        title: "Regular Distributions",
        description: "Receive periodic income distributions from rental earnings",
        icon: <Banknote className="w-8 h-8 text-yellow-600" />
      },
      {
        title: "Professional Management",
        description: "Properties managed by experienced real estate professionals",
        icon: <Briefcase className="w-8 h-8 text-purple-600" />
      },
      {
        title: "Tax Efficiency",
        description: "Potential tax advantages with pass-through structure",
        icon: <Receipt className="w-8 h-8 text-indigo-600" />
      },
      {
        title: "SEBI Regulated",
        description: "Regulated by SEBI with investor protection measures",
        icon: <Shield className="w-8 h-8 text-red-600" />
      }
    ],
    venture: [
      {
        title: "High Growth Potential",
        description: "Access to early-stage real estate projects with exponential growth potential",
        icon: <Rocket className="w-8 h-8 text-blue-600" />
      },
      {
        title: "Innovative Projects",
        description: "Invest in cutting-edge developments like smart cities and tech parks",
        icon: <Lightbulb className="w-8 h-8 text-green-600" />
      },
      {
        title: "Higher Returns",
        description: "Target returns of 18-25% through strategic venture investments",
        icon: <TrendingUp className="w-8 h-8 text-yellow-600" />
      },
      {
        title: "Portfolio Diversification",
        description: "Add alternative real estate assets to balance your investment portfolio",
        icon: <Layers className="w-8 h-8 text-purple-600" />
      },
      {
        title: "Expert Curation",
        description: "Projects vetted by our team of real estate and finance experts",
        icon: <Star className="w-8 h-8 text-indigo-600" />
      },
      {
        title: "Early Access",
        description: "Get exclusive access to pre-launch and off-market opportunities",
        icon: <Search className="w-8 h-8 text-red-600" />
      }
    ]
  };

  // Investment type data
  const investmentTypes = [
    {
      id: "fractional",
      title: "Fractional Investment",
      description: "Direct ownership in high-value properties",
      icon: <Building2 className="w-6 h-6" />
    },
    {
      id: "reit",
      title: "REIT / SM REIT",
      description: "Diversified portfolio through Real Estate Investment Trusts",
      icon: <Landmark className="w-6 h-6" />
    },
    {
      id: "venture",
      title: "Venture Investment",
      description: "High-growth potential in emerging real estate ventures",
      icon: <Rocket className="w-6 h-6" />
    }
  ];

  // REIT type options
  const reitTypes = [
    {
      id: "reit",
      title: "REIT",
      description: "Large, diversified real estate portfolios"
    },
    {
      id: "smreit",
      title: "SM REIT",
      description: "Small, focused real estate portfolios"
    }
  ];

  // Get the current features based on active tab and REIT type
  const getCurrentFeatures = () => {
    if (activeTab === "reit") {
      return investmentFeatures[reitType];
    }
    return investmentFeatures[activeTab];
  };

  return (
    <div className="py-12 bg-gradient-to-b from-white to-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Investment Options
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Choose the investment path that aligns with your financial goals and risk appetite
          </p>
        </div>

        {/* Tabs */}
        <div className="flex justify-center mb-10">
          <div className="inline-flex bg-white rounded-lg shadow p-1 border border-gray-200">
            {investmentTypes.map((type) => (
              <button
                key={type.id}
                onClick={() => setActiveTab(type.id)}
                className={`flex items-center px-4 py-3 rounded-md text-sm font-medium transition-all duration-200 ${
                  activeTab === type.id
                    ? "bg-blue-900 text-white shadow"
                    : "text-gray-700 hover:text-gray-900 hover:bg-gray-100"
                }`}
              >
                <span className="mr-2">{type.icon}</span>
                {type.title}
              </button>
            ))}
          </div>
        </div>

        {/* REIT/SM REIT Toggle - Only show when REIT tab is active */}
        {activeTab === "reit" && (
          <div className="flex justify-center mb-8">
            <div className="inline-flex bg-white rounded-lg shadow p-1 border border-gray-200">
              {reitTypes.map((type) => (
                <button
                  key={type.id}
                  onClick={() => setReitType(type.id)}
                  className={`flex flex-col items-center px-4 py-3 rounded-md text-sm font-medium transition-all duration-200 ${
                    reitType === type.id
                      ? "bg-blue-900 text-white shadow"
                      : "text-gray-700 hover:text-gray-900 hover:bg-gray-100"
                  }`}
                >
                  <span className="font-semibold">{type.title}</span>
                  <span className="text-xs opacity-80 mt-1">{type.description}</span>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Tab Content */}
        <div className="mb-16">
          {/* Description for active tab */}
          <div className="text-center mb-10 max-w-3xl mx-auto">
            <h3 className="text-2xl font-bold text-gray-900 mb-3">
              {activeTab === "reit" 
                ? reitTypes.find(t => t.id === reitType)?.title + " Investment"
                : investmentTypes.find(t => t.id === activeTab)?.title}
            </h3>
            <p className="text-gray-600">
              {activeTab === "reit" 
                ? reitTypes.find(t => t.id === reitType)?.description
                : investmentTypes.find(t => t.id === activeTab)?.description}
            </p>
          </div>

          {/* Feature Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {getCurrentFeatures().map((feature, index) => (
              <Card 
                key={index} 
                className="overflow-hidden border border-gray-200 shadow-sm hover:shadow-md transition-all duration-300 hover:-translate-y-1"
              >
                <CardContent className="p-6">
                  <div className="flex items-start mb-4">
                    <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-blue-50 text-blue-700 mr-4">
                      {feature.icon}
                    </div>
                    <h4 className="text-lg font-semibold text-gray-900">{feature.title}</h4>
                  </div>
                  <p className="text-gray-600 text-sm">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}